### ISSUE TITLE
Custom Training Issue

### ISSUE THREAD

**Issue by adamdavidcole** [Janspiry/Palette-Image-to-Image-Diffusion-Models#33]
Hello! 

I am trying to create a custom image-to-image model. I've set up a custom dataset that pulls `gt_image` from one folder and `cond_image` from a parallel folder. 

```
 img_path = f"{self.data_root}/train_A/{file_name}"
cond_image_path = f"{self.data_root}/train_B/{file_name}"

img = self.tfs(self.loader(img_path))
cond_image = self.tfs(self.loader(cond_image_path))
```

I've trained the model for 65 epochs and while the images are starting to converge nicely, they look like they are recreating the gt_image and not the conditional image.

I've done some debugging to ensure the image data is correct for both the `gt` and `cond` image in `train_step()`. Is there another place worth double-checking that the data flow is correct? 

Is it normal for the outputs to match the original data set at first before beginning to approximate the conditional image? Should I just keep training and hope to see an improvement?

Thanks for this repo! 

**Input image**
![20382](https://user-images.githubusercontent.com/5685294/182031270-16b95373-48de-48e5-863c-7656c2cf53f7.jpg)

**Expected output**
![20382](https://user-images.githubusercontent.com/5685294/182031263-9cdc17e2-e36a-4d70-9faf-bc804ada8bcd.jpg)

**Actual output**
![20382 (1)](https://user-images.githubusercontent.com/5685294/182031276-65e8fab4-e399-4e34-8ca3-769c54a9c110.jpg)

**Comment by Janspiry** [comment]
Hey, thanks for your attention.
1. I think this check is enough since condition images just set at https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/blob/136b29f58d0af6e5db9f3655d2891f5a855fcdaa/models/model.py#L59
Maybe you can also check the modified code about training pipeline.

2. From the information given, it is harder to get the Expected output, what is the conditional input you give ?

**Comment by Janspiry** [comment]
Feel free to reopen the issue if there is any question.
